# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       xorg-x11-xtrans-devel
Summary:    X.Org X11 developmental X transport library
Version:    1.2.5
Release:    1
Group:      System/Libraries
License:    MIT/X11
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/lib/xtrans-%{version}.tar.bz2
Source100:  xorg-x11-xtrans-devel.yaml
BuildRequires:  xorg-x11-util-macros

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Description: %{summary}



%prep
%setup -q -n xtrans-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING NEWS README
%dir %{_includedir}/X11
%dir %{_includedir}/X11/Xtrans
%{_includedir}/X11/Xtrans/Xtrans.c
%{_includedir}/X11/Xtrans/Xtrans.h
%{_includedir}/X11/Xtrans/Xtransint.h
%{_includedir}/X11/Xtrans/Xtranslcl.c
%{_includedir}/X11/Xtrans/Xtranssock.c
%{_includedir}/X11/Xtrans/Xtranstli.c
%{_includedir}/X11/Xtrans/Xtransutil.c
%{_includedir}/X11/Xtrans/transport.c
%{_datadir}/pkgconfig/xtrans.pc
%{_datadir}/aclocal/xtrans.m4
# << files


